version: "3.9" # Specifies the version of the Docker Compose file format

name: "todo-api" # Name of the Docker Compose project

services:
  api:
    build:
      context: . # Specifies the build context, which is the current directory
      dockerfile: Dockerfile # The Dockerfile to use for building the image
    ports:
      - "8000:8000" # Maps port 8000 on the host to port 8000 in the container
    depends_on:
      - postgresdb # Ensures that the postgresdb service is started before this service

  postgresdb:
    image: postgres:latest # Uses the official PostgreSQL image from Docker Hub
    restart: always # Always restart the container if it stops
    container_name: PostgresCont # Sets a custom name for the PostgreSQL container
    environment:
      - POSTGRES_USER=ziakhan # Sets the PostgreSQL user
      - POSTGRES_PASSWORD=my_password # Sets the PostgreSQL password
      - POSTGRES_DB=mydatabase # Sets the name of the PostgreSQL database
    ports:
      - "5433:5432" # Maps port 5433 on the host to port 5432 in the container
    volumes:
      - postgres_db:/var/lib/postgresql/data # Mounts a volume for persistent storage of PostgreSQL data
  
  
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker


volumes:
  postgres_db:
    driver: local # Specifies the use of a local driver for the volume

networks:
  default:
    driver: bridge # Uses the default bridge network for container communication
